import type { ExtractorOutputV14 } from '../../openai/extractor-v1.4.types.js';
import { SOURCE_BLOCK_RAW } from '../../utils/source-blocks.js';

function base(): ExtractorOutputV14 {
  return {
    schema_version: '1.4',
    entity_mentions: [],
    aliases: [],
    events: [],
    correction_signals: [],
    assertions: [],
    task_signals: [],
    clarification_candidates: [],
    review_hints: [],
    extraction_notes: [],
  };
}

export const FIXED_EXTRACTOR_FIXTURES: Record<string, ExtractorOutputV14> = {
  'v14-panorama-static': {
    ...base(),
    entity_mentions: [
      {
        mention_text: 'Alex Costa',
        suggested_entity_type: 'person',
        source_excerpt: 'Alex Costa (Ace)',
        confidence: 0.95,
      },
      {
        mention_text: 'Dana Silva',
        suggested_entity_type: 'person',
        source_excerpt: 'Dana Silva (Dee)',
        confidence: 0.95,
      },
      {
        mention_text: 'Chris Oliveira',
        suggested_entity_type: 'person',
        source_excerpt: 'Chris Oliveira (Cri)',
        confidence: 0.95,
      },
    ],
    aliases: [
      {
        alias: 'Ace',
        target_reference: 'Alex Costa',
        negated_former_references: [],
        source_excerpt: 'Alex Costa (Ace)',
        confidence: 0.9,
      },
      {
        alias: 'Dee',
        target_reference: 'Dana Silva',
        negated_former_references: [],
        source_excerpt: 'Dana Silva (Dee)',
        confidence: 0.9,
      },
      {
        alias: 'Cri',
        target_reference: 'Chris Oliveira',
        negated_former_references: [],
        source_excerpt: 'Chris Oliveira (Cri)',
        confidence: 0.9,
      },
    ],
    events: [],
    assertions: [],
  },
  'v14-static-preferences': {
    ...base(),
    entity_mentions: [
      {
        mention_text: 'Alex Costa',
        suggested_entity_type: 'person',
        source_excerpt: 'Alex prefere reuniões',
        confidence: 0.9,
      },
    ],
    assertions: [
      {
        assertion_kind: 'opinion',
        subject_reference: 'Alex Costa',
        predicate: 'prefere',
        object_reference: null,
        value_text: 'reuniões pela manhã',
        related_entity_references: ['Alex Costa'],
        source_excerpt: 'Alex prefere reuniões pela manhã',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.88,
      },
    ],
    events: [],
  },
  'v14-alias-explicit': {
    ...base(),
    aliases: [
      {
        alias: 'Tick',
        target_reference: 'Alex Costa',
        negated_former_references: [],
        source_excerpt: 'Tick se refere a Alex Costa',
        confidence: 0.92,
      },
    ],
  },
  'v14-alias-negated': {
    ...base(),
    aliases: [
      {
        alias: 'Zeta-1',
        target_reference: 'Gabriel Nova',
        negated_former_references: ['Helcio Zeta'],
        source_excerpt: 'Zeta-1 agora se refere a Gabriel Nova',
        confidence: 0.9,
      },
    ],
  },
  'v14-alias-reassignment': {
    ...base(),
    aliases: [
      {
        alias: 'Fox-1',
        target_reference: 'Pat Lee',
        negated_former_references: ['Sam Fox'],
        source_excerpt: 'Fox-1 agora se refere a Pat Lee',
        confidence: 0.9,
      },
    ],
  },
  'v14-meeting': {
    ...base(),
    events: [
      {
        event_kind: 'meeting',
        title: 'Reunião integração módulo 2',
        source_excerpt: 'participou da reunião',
        occurred_at: null,
        episodic_confidence: 0.85,
        related_entities: [
          {
            entity_reference: 'Chris Oliveira',
            relation_type: 'participant',
            role: null,
          },
        ],
      },
    ],
  },
  'v14-confirmation': {
    ...base(),
    events: [
      {
        event_kind: 'confirmation',
        title: 'Confirmação envio contrato',
        source_excerpt: 'confirmou o envio',
        occurred_at: null,
        episodic_confidence: 0.88,
        related_entities: [
          {
            entity_reference: 'Dana Silva',
            relation_type: 'sender',
            role: null,
          },
        ],
      },
    ],
  },
  'v14-correction-participant': {
    ...base(),
    events: [
      {
        event_kind: 'meeting',
        title: 'Reunião 2',
        source_excerpt: 'Bruno Vega participou',
        occurred_at: null,
        episodic_confidence: 0.85,
        related_entities: [
          {
            entity_reference: 'Bruno Vega',
            relation_type: 'participant',
            role: null,
          },
        ],
      },
    ],
    correction_signals: [
      {
        correction_type: 'replace_subject',
        previous_reference: 'Chris Oliveira',
        current_reference: 'Bruno Vega',
        source_excerpt: 'Bruno Vega participou',
        source_block_reference: '[SOURCE_BLOCK:correction:00000000-0000-4000-8000-000000000002]',
        confidence: 0.92,
      },
    ],
  },
  'v14-correction-sender': {
    ...base(),
    events: [
      {
        event_kind: 'document_sent',
        title: 'Envio relatório',
        source_excerpt: 'enviado por Dana Silva',
        occurred_at: null,
        episodic_confidence: 0.85,
        related_entities: [
          {
            entity_reference: 'Dana Silva',
            relation_type: 'sender',
            role: null,
          },
        ],
      },
    ],
    correction_signals: [
      {
        correction_type: 'replace_object',
        previous_reference: 'Chris Oliveira',
        current_reference: 'Dana Silva',
        source_excerpt: 'enviado por Dana Silva',
        source_block_reference: '[SOURCE_BLOCK:correction:00000000-0000-4000-8000-000000000003]',
        confidence: 0.92,
      },
    ],
  },
  'v14-task-open': {
    ...base(),
    task_signals: [
      {
        operation: 'create',
        task_reference: null,
        title: 'Enviar relatório Q2',
        task_kind: 'delivery',
        status_signal: 'open',
        assignee_reference: 'Dana Silva',
        target_reference: 'relatório Q2',
        project_reference: 'Projeto Atlas',
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Dana deve enviar',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-task-blocked': {
    ...base(),
    task_signals: [
      {
        operation: 'update_blocker',
        task_reference: 'Entrega módulo API',
        title: 'Entrega módulo API',
        task_kind: 'delivery',
        status_signal: 'blocked',
        assignee_reference: 'Alex Costa',
        target_reference: 'módulo API',
        project_reference: 'Projeto Atlas',
        due_at: null,
        blocked_reason: 'aguardando aprovação',
        source_excerpt: 'bloqueada aguardando aprovação',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-task-due-date-change': {
    ...base(),
    task_signals: [
      {
        operation: 'update_due_date',
        task_reference: 'tarefa QA',
        title: null,
        task_kind: null,
        status_signal: null,
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: 'segunda-feira',
        blocked_reason: null,
        source_excerpt: 'Prazo da tarefa de QA mudou para segunda-feira',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-task-assignee-change': {
    ...base(),
    task_signals: [
      {
        operation: 'update_assignee',
        task_reference: 'tarefa de migração',
        title: null,
        task_kind: null,
        status_signal: null,
        assignee_reference: 'Dana Silva',
        target_reference: null,
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Tarefa passou para Dana Silva',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-task-completed': {
    ...base(),
    task_signals: [
      {
        operation: 'complete',
        task_reference: 'migração',
        title: null,
        task_kind: null,
        status_signal: 'completed',
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Concluída a tarefa de migração',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-task-cancel': {
    ...base(),
    task_signals: [
      {
        operation: 'cancel',
        task_reference: 'deploy beta',
        title: null,
        task_kind: null,
        status_signal: 'cancelled',
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Cancelada a tarefa de deploy beta',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-project-status': {
    ...base(),
    assertions: [
      {
        assertion_kind: 'status_update',
        subject_reference: 'Projeto Atlas',
        predicate: 'entrou_em_fase',
        object_reference: null,
        value_text: 'homologação',
        related_entity_references: ['Projeto Atlas'],
        source_excerpt: 'Projeto Atlas entrou em homologação',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-fc-task-new': {
    ...base(),
    task_signals: [
      {
        operation: 'create',
        task_reference: null,
        title: 'Revisar contrato',
        task_kind: 'review',
        status_signal: 'open',
        assignee_reference: null,
        target_reference: 'contrato',
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Precisamos revisar o contrato',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
    clarification_candidates: [
      {
        target_type: 'task',
        target_reference: 'Revisar contrato',
        issue_type: 'missing_assignee',
        question: 'Quem é o responsável?',
        reason: 'sem assignee',
        priority: 'medium',
        blocking_scope: 'task_execution',
        suggested_answers: [],
        source_excerpt: 'Precisamos revisar o contrato',
        source_block_reference: null,
        confidence: 0.7,
      },
    ],
  },
  'v14-fc-project-new': {
    ...base(),
    task_signals: [
      {
        operation: 'create',
        task_reference: null,
        title: 'Integração com Tagna',
        task_kind: 'delivery',
        status_signal: 'open',
        assignee_reference: null,
        target_reference: 'Tagna',
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Começamos a integração com a Tagna',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-fc-status-new': {
    ...base(),
    assertions: [
      {
        assertion_kind: 'status_update',
        subject_reference: 'Projeto Atlas',
        predicate: 'em_fase',
        object_reference: null,
        value_text: 'homologação',
        related_entity_references: ['Projeto Atlas'],
        source_excerpt: 'Projeto Atlas está em homologação',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-fc-blocked-new': {
    ...base(),
    task_signals: [
      {
        operation: 'update_blocker',
        task_reference: 'revisão',
        title: null,
        task_kind: null,
        status_signal: 'blocked',
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: null,
        blocked_reason: 'aguardando acesso',
        source_excerpt: 'Revisão bloqueada aguardando acesso',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-ctx-due-date-unique': {
    ...base(),
    task_signals: [
      {
        operation: 'update_due_date',
        task_reference: 'revisão',
        title: null,
        task_kind: null,
        status_signal: null,
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: 'sexta',
        blocked_reason: null,
        source_excerpt: 'O prazo da revisão mudou para sexta',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-ctx-assignee-unique': {
    ...base(),
    task_signals: [
      {
        operation: 'update_assignee',
        task_reference: 'integração',
        title: null,
        task_kind: null,
        status_signal: null,
        assignee_reference: 'Dana Silva',
        target_reference: null,
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Agora Dana vai acompanhar',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-ctx-complete-unique': {
    ...base(),
    task_signals: [
      {
        operation: 'complete',
        task_reference: 'cobrar fornecedor',
        title: null,
        task_kind: null,
        status_signal: 'completed',
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: null,
        blocked_reason: null,
        source_excerpt: 'Pode marcar como concluído',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-ctx-due-date-ambiguous': {
    ...base(),
    task_signals: [
      {
        operation: 'update_due_date',
        task_reference: 'revisão',
        title: null,
        task_kind: null,
        status_signal: null,
        assignee_reference: null,
        target_reference: null,
        project_reference: null,
        due_at: 'sexta',
        blocked_reason: null,
        source_excerpt: 'O prazo da revisão mudou para sexta',
        source_block_reference: SOURCE_BLOCK_RAW,
        confidence: 0.9,
      },
    ],
  },
  'v14-ambiguous-identity': {
    ...base(),
    entity_mentions: [
      {
        mention_text: 'Chris',
        suggested_entity_type: 'person',
        source_excerpt: 'enviado por Chris',
        confidence: 0.7,
      },
    ],
    clarification_candidates: [
      {
        target_type: 'entity',
        target_reference: 'Chris',
        issue_type: 'ambiguous_identity',
        question: 'Chris Oliveira ou Chris Mendes?',
        reason: 'dois Chris no contexto',
        priority: 'high',
        blocking_scope: 'knowledge_confirmation',
        suggested_answers: ['Chris Oliveira', 'Chris Mendes'],
        source_excerpt: 'enviado por Chris',
        source_block_reference: null,
        confidence: 0.85,
      },
    ],
  },
};
