/** JSON Schema for OpenAI Structured Outputs — extractor-v1.2 */
export const extractorJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    schema_version: { type: 'string' },
    inbox_item_id: { type: 'string' },
    events: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          event_type: { type: 'string' },
          description: { type: 'string' },
          occurred_at: { type: ['string', 'null'] },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
          entity_names: {
            type: 'array',
            items: { type: 'string' },
          },
        },
        required: [
          'event_type',
          'description',
          'occurred_at',
          'source_excerpt',
          'confidence',
          'entity_names',
        ],
      },
    },
    entities: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          name: { type: 'string' },
          entity_type: {
            type: 'string',
            enum: [
              'person',
              'company',
              'project',
              'product',
              'topic',
              'document',
              'location',
              'other',
            ],
          },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
        },
        required: ['name', 'entity_type', 'source_excerpt', 'confidence'],
      },
    },
    assertions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          assertion_type: {
            type: 'string',
            enum: [
              'fact',
              'hypothesis',
              'opinion',
              'decision',
              'commitment',
              'question',
              'assumption',
              'recommendation',
            ],
          },
          content: { type: 'string' },
          status: {
            type: 'string',
            enum: [
              'unverified',
              'supported',
              'confirmed',
              'contested',
              'invalidated',
              'superseded',
            ],
          },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
        },
        required: ['assertion_type', 'content', 'status', 'source_excerpt', 'confidence'],
      },
    },
    tasks: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          title: { type: 'string' },
          description: { type: ['string', 'null'] },
          due_at: { type: ['string', 'null'] },
          temporal_reference_text: { type: ['string', 'null'] },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
          is_commitment: { type: 'boolean' },
        },
        required: [
          'title',
          'description',
          'due_at',
          'temporal_reference_text',
          'source_excerpt',
          'confidence',
          'is_commitment',
        ],
      },
    },
    clarification_requests: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          target_type: {
            type: 'string',
            enum: ['entity', 'event', 'assertion', 'task', 'external_action', 'other'],
          },
          target_reference: { type: 'string' },
          issue_type: {
            type: 'string',
            enum: [
              'ambiguous_entity_type',
              'ambiguous_entity_identity',
              'missing_task_target',
              'missing_external_action_target',
              'missing_date',
              'missing_context',
              'other',
            ],
          },
          question: { type: 'string' },
          reason: { type: 'string' },
          priority: { type: 'string', enum: ['low', 'medium', 'high'] },
          blocking_scope: {
            type: 'string',
            enum: ['none', 'knowledge_confirmation', 'task_execution', 'external_action'],
          },
          suggested_answers: { type: 'array', items: { type: 'string' } },
          source_excerpt: { type: 'string' },
        },
        required: [
          'target_type',
          'target_reference',
          'issue_type',
          'question',
          'reason',
          'priority',
          'blocking_scope',
          'suggested_answers',
          'source_excerpt',
        ],
      },
    },
    requires_review: { type: 'boolean' },
    review_reasons: { type: 'array', items: { type: 'string' } },
    processing_notes: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'schema_version',
    'inbox_item_id',
    'events',
    'entities',
    'assertions',
    'tasks',
    'clarification_requests',
    'requires_review',
    'review_reasons',
    'processing_notes',
  ],
} as const;
