import { CLARIFICATION_ISSUE_TYPES } from './extractor-v1.4.types.js';

/** JSON Schema for OpenAI Structured Outputs — extractor-v1.4 */
export const extractorV14JsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    schema_version: { type: 'string', enum: ['1.4'] },
    entity_mentions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          mention_text: { type: 'string' },
          suggested_entity_type: {
            type: 'string',
            enum: [
              'person',
              'company',
              'project',
              'product',
              'topic',
              'document',
              'location',
              'temporal',
              'measurement',
              'other',
            ],
          },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
        },
        required: ['mention_text', 'suggested_entity_type', 'source_excerpt', 'confidence'],
      },
    },
    aliases: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          alias: { type: 'string' },
          target_reference: { type: 'string' },
          negated_former_references: { type: 'array', items: { type: 'string' } },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
        },
        required: [
          'alias',
          'target_reference',
          'negated_former_references',
          'source_excerpt',
          'confidence',
        ],
      },
    },
    events: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          event_kind: {
            type: 'string',
            enum: [
              'meeting',
              'confirmation',
              'decision',
              'document_sent',
              'presentation',
              'commitment',
              'change',
              'correction',
              'other',
            ],
          },
          title: { type: 'string' },
          source_excerpt: { type: 'string' },
          occurred_at: { type: ['string', 'null'] },
          episodic_confidence: { type: 'number' },
          related_entities: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              properties: {
                entity_reference: { type: 'string' },
                relation_type: {
                  type: 'string',
                  enum: [
                    'participant',
                    'subject',
                    'mentioned',
                    'sender',
                    'recipient',
                    'other',
                  ],
                },
                role: { type: ['string', 'null'] },
              },
              required: ['entity_reference', 'relation_type', 'role'],
            },
          },
        },
        required: [
          'event_kind',
          'title',
          'source_excerpt',
          'occurred_at',
          'episodic_confidence',
          'related_entities',
        ],
      },
    },
    correction_signals: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          correction_type: {
            type: 'string',
            enum: [
              'replace_subject',
              'replace_object',
              'invalidate_assertion',
              'invalidate_alias',
              'other',
            ],
          },
          previous_reference: { type: ['string', 'null'] },
          current_reference: { type: ['string', 'null'] },
          source_excerpt: { type: 'string' },
          source_block_reference: { type: ['string', 'null'] },
          confidence: { type: 'number' },
        },
        required: [
          'correction_type',
          'previous_reference',
          'current_reference',
          'source_excerpt',
          'source_block_reference',
          'confidence',
        ],
      },
    },
    assertions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          assertion_kind: {
            type: 'string',
            enum: [
              'fact',
              'hypothesis',
              'opinion',
              'decision',
              'commitment',
              'status_update',
              'other',
            ],
          },
          subject_reference: { type: 'string' },
          predicate: { type: 'string' },
          object_reference: { type: ['string', 'null'] },
          value_text: { type: ['string', 'null'] },
          related_entity_references: { type: 'array', items: { type: 'string' } },
          source_excerpt: { type: 'string' },
          source_block_reference: { type: ['string', 'null'] },
          confidence: { type: 'number' },
        },
        required: [
          'assertion_kind',
          'subject_reference',
          'predicate',
          'object_reference',
          'value_text',
          'related_entity_references',
          'source_excerpt',
          'source_block_reference',
          'confidence',
        ],
      },
    },
    task_signals: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          operation: {
            type: 'string',
            enum: [
              'create',
              'update_status',
              'update_due_date',
              'update_assignee',
              'update_blocker',
              'complete',
              'cancel',
            ],
          },
          task_reference: { type: ['string', 'null'] },
          title: { type: ['string', 'null'] },
          task_kind: {
            type: ['string', 'null'],
            enum: [
              'follow_up',
              'delivery',
              'decision',
              'review',
              'external_action',
              'other',
              null,
            ],
          },
          status_signal: {
            type: ['string', 'null'],
            enum: ['open', 'completed', 'cancelled', 'blocked', 'unknown', null],
          },
          assignee_reference: { type: ['string', 'null'] },
          target_reference: { type: ['string', 'null'] },
          project_reference: { type: ['string', 'null'] },
          due_at: { type: ['string', 'null'] },
          blocked_reason: { type: ['string', 'null'] },
          source_excerpt: { type: 'string' },
          source_block_reference: { type: ['string', 'null'] },
          confidence: { type: 'number' },
        },
        required: [
          'operation',
          'task_reference',
          'title',
          'task_kind',
          'status_signal',
          'assignee_reference',
          'target_reference',
          'project_reference',
          'due_at',
          'blocked_reason',
          'source_excerpt',
          'source_block_reference',
          'confidence',
        ],
      },
    },
    clarification_candidates: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          target_type: {
            type: 'string',
            enum: ['entity', 'event', 'assertion', 'task', 'external_action', 'other'],
          },
          target_reference: { type: 'string' },
          issue_type: {
            type: 'string',
            enum: [...CLARIFICATION_ISSUE_TYPES],
          },
          question: { type: 'string' },
          reason: { type: 'string' },
          priority: { type: 'string', enum: ['low', 'medium', 'high'] },
          blocking_scope: {
            type: 'string',
            enum: ['none', 'knowledge_confirmation', 'task_execution', 'external_action'],
          },
          suggested_answers: { type: 'array', items: { type: 'string' } },
          source_excerpt: { type: 'string' },
          source_block_reference: { type: ['string', 'null'] },
          confidence: { type: 'number' },
        },
        required: [
          'target_type',
          'target_reference',
          'issue_type',
          'question',
          'reason',
          'priority',
          'blocking_scope',
          'suggested_answers',
          'source_excerpt',
          'source_block_reference',
          'confidence',
        ],
      },
    },
    review_hints: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          issue_type: {
            type: 'string',
            enum: [
              'ambiguous_identity',
              'ambiguous_entity_type',
              'possible_contradiction',
              'low_confidence_event',
              'unresolved_reference',
              'other',
            ],
          },
          target_reference: { type: ['string', 'null'] },
          reason: { type: 'string' },
          source_excerpt: { type: 'string' },
          confidence: { type: 'number' },
        },
        required: ['issue_type', 'target_reference', 'reason', 'source_excerpt', 'confidence'],
      },
    },
    extraction_notes: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'schema_version',
    'entity_mentions',
    'aliases',
    'events',
    'correction_signals',
    'assertions',
    'task_signals',
    'clarification_candidates',
    'review_hints',
    'extraction_notes',
  ],
} as const;
